apiVersion: v2
appVersion: v10.1
description: A Helm chart for XL Release
name: digitalai-release-ocp
version: 10.1

dependencies:

- name: postgresql
  version: 9.8.5
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.install

- name: rabbitmq
  version: 8.6.1
  repository: "https://charts.bitnami.com/bitnami"
  condition: rabbitmq.install

