{{- if and .Values.rabbitmq.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.subchart" . }}-release
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  rabbitmq-erlang-cookie: DEPLOYRABBITMQCLUSTER
  release_load_definition.json: |
    {
      "users": [
        {
          "name": "{{ .Values.rabbitmq.auth.username }}",
          "password": "{{ .Values.rabbitmq.auth.password }}",
          "tags": "administrator"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "{{ .Values.rabbitmq.auth.username }}",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "global_parameters": [
        {
          "name": "cluster_name",
          "value": ""
        }
      ]
    }
{{- end }}
