{{- if and .Values.route.Enabled -}}
{{- $fullName := include "xl-release.fullname" . -}}
{{- $routePath := .Values.route.path -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "xl-release.name" . }}
    chart: {{ template "xl-release.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- range .Values.route.hosts }}
  host: {{ . }}
  path: {{ $routePath }}
  to:
    kind: Service
    name: {{ $fullName }}
  port:
    targetPort: xlr-http
{{- if $.Values.route.tls }}
  tls:
  {{- with $.Values.route.tls }}
    key: |-
{{ .key | indent 6 }}
    certificate: |-
{{ .certificate | indent 6 }}
    caCertificate: |-
{{ .caCertificate | indent 6 }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy }}
  {{- end }}
    termination: edge
{{- end }}
{{- end }}
{{- end }}
